
class params:
    def __init__(self):
        # int16_t kVdd;
        self.kVdd = int()
        # int16_t vdd25;
        self.vdd25 = int()
        # float KvPTAT;
        self.KvPTAT = float()
        # float KtPTAT;
        self.KtPTAT = float()
        # uint16_t vPTAT25;
        self.vPTAT25 = int()
        # float alphaPTAT;
        self.alphaPTAT = float()
        # int16_t gainEE;
        self.gainEE = int()
        # float tgc;
        self.tgc = float()
        # float cpKv;
        self.cpKv = float()
        # float cpKta;
        self.cpKta = float()
        # uint8_t resolutionEE;
        self.resolutionEE = int()
        # uint8_t calibrationModeEE;
        self.calibrationModeEE = int()
        # float KsTa;
        self.KsTa = float()
        # float ksTo[4];
        self.ksTo = 4*[float()]
        # int16_t ct[4];
        self.ct = 4*[int()]
        # float alpha[768];
        self.alpha = 768*[float()]
        # int16_t offset[768];    
        self.offset = 768*[int()]
        # float kta[768];    
        self.kta = 768*[float()]
        # float kv[768];
        self.kv = 768*[float()]
        # float cpAlpha[2];
        self.cpAlpha = 2*[float()]
        # int16_t cpOffset[2];
        self.cpOffset = 2*[int()]
        # float ilChessC[3]; 
        self.ilChessC = 3*[float()]
        # uint16_t brokenPixels[5];
        self.brokenPixels = 5*[int()]
        # uint16_t outlierPixels[5];
        self.outlierPixels = 5*[int()]
         